spring:
  application:
    name: person-front
    alias: ${SERVICE_ALIAS:front}
  thymeleaf:
    cache: false
  cloud:
    consul:
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${SERVER_PORT:8080}:${random.value}
        prefer-ip-address: false
        fail-fast: false
        register: true
      host: localhost
      port: 8500
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: person-front
      instance: ${SERVER_PORT:8080}

server:
  port: ${SERVER_PORT:8080}

logstash:
  host: localhost

logging:
  config: classpath:log-config.xml
  level:
    org.thymeleaf: WARN
    io.github.joxebus: DEBUG
    org.springframework.cloud.consul: DEBUG

# This is a configuration defined to setup the RestTemplate
rest:
  consul:
    root:
      uri: "http://person-service-client"
