spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: consul
    password: example
    url: jdbc:mysql://mysql:3306/consul-example?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  cloud:
    consul:
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${SERVER_PORT:8081}:${random.value}
        prefer-ip-address: false
      host: consul
      port: 8500

server:
  port: ${SERVER_PORT:8081}

logstash:
  host: logstash

logging:
  config: classpath:log-config.xml
  level:
    io.github.joxebus: INFO
