spring:
  application:
    name: person-service-client
    alias: ${SERVICE_ALIAS}
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:file:~/consul-example;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
  cloud:
    consul:
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${SERVER_PORT:8081}:${random.value}
        hostname: ${HOSTNAME:localhost}
        prefer-ip-address: false
        fail-fast: false
        register: true
      host: localhost
      port: 8500
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

server:
  port: ${SERVER_PORT:8081}

logstash:
  host: localhost

logging:
  config: classpath:log-config.xml
  level:
    io.github.joxebus: DEBUG
    org.springframework.cloud.consul: DEBUG
